#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/config.json"
STYLE="$HOME/.config/hypr/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
  waybar --log-level error --config ${CONFIG} --style ${STYLE}
fi
