#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/config.json"
STYLE="$HOME/.config/hypr/waybar/style-dark.css"

if [[ ! $(pidof waybar) ]]; then
  waybar --log-level error --config ${CONFIG} --style ${STYLE}
else
  kill $(pidof waybar)
  waybar --log-level error --config ${CONFIG} --style ${STYLE}
fi
